### ISSUE TITLE
$driver_options['typeMap'] 

### ISSUE THREAD

**Issue by iNDicat0r** [leroy-merlin-br/mongolid#76]
Hi

I want to utilize the mongodb connection to the server through out other packages that i am using in my slim3 application. The problem is that your package uses

`$driver_options['typeMap'] = ['array' => 'array', 'document' => 'array'];`

and some other libraries that i use dont like the above settings, and when i disable this they work simply fine,  so would like to know if i disable this option is there going to be any problem with your package ?

**Comment by rscafi** [comment]
ping @Zizaco

**Comment by Zizaco** [comment]
@iNDicat0r Today, mongolid utilizes arrays instead of `stdClass` objects internally. That's why the connection is handled that way (with those driver options). For now what you can do is to open a new connection without the typeMap option to utilize with the other libraries.

The ideal solution would be to wrap the communication with the driver (somewhere near the `DataMapper`) to convert any array into `stdClass` object (and vice-versa) before persisting or retrieving data in order not to need these strict driver options.

We may make that change in the future. Also you can send a pull request if you wish :smile:

**Comment by iNDicat0r** [comment]
Alright thanks I will try now.

**Comment by ravanscafi** [comment]
@iNDicat0r as it is not currently our use case, we will not implement it but feel free to send PRs if you still need it.
